<?php

namespace Finance\OperationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransferBetweenAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferBetweenAccountRepository extends EntityRepository
{
}
