nutri_recipe:
    resource: "@NutriRecipeBundle/Controller/"
    type:     annotation
    prefix:   /nutri/recipe/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oliorga_app:
    resource: "@OliorgaAppBundle/Controller/"
    type:     annotation
    prefix:   /

nutri_ingredient:
    resource: "@NutriIngredientBundle/Controller/"
    type:     annotation
    prefix:   /nutri/ingredient/


shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'