finance_institution:
    resource: "@FinanceInstitutionBundle/Controller/"
    type:     annotation
    prefix:   /finance/institution/

finance_account:
    resource: "@FinanceAccountBundle/Controller/"
    type:     annotation
    prefix:   /finance/account/

finance_operation:
    resource: "@FinanceOperationBundle/Controller/"
    type:     annotation
    prefix:   /finance/operation/

nutri_recipe:
    resource: "@NutriRecipeBundle/Controller/"
    type:     annotation
    prefix:   /nutri/recipe/

nutri_ingredient:
    resource: "@NutriIngredientBundle/Controller/"
    type:     annotation
    prefix:   /nutri/ingredient/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oliorga_app:
    resource: "@OliorgaAppBundle/Controller/"
    type:     annotation
    prefix:   /


shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'