services:
    financeoperation.boursoramaccpimporter:
        class: Finance\OperationBundle\Service\Importer\BoursoramaCcpImporter
        arguments: [ @doctrine, %operation.boursoramaccpimporter.stringtoentityidarray% ]
    