<?php

namespace Finance\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssuranceVieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssuranceVieRepository extends EntityRepository
{
}
