<?php

namespace Finance\InstitutionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InsurerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsurerRepository extends EntityRepository
{
}
