<?php

namespace Nutri\IngredientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
    public function getNamesById() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        
        $qb->select('i.id');
        $qb->addSelect('i.name');     
        
        $qb->from('NutriIngredientBundle:Ingredient','i');        
        $qb->setMaxResults(0);
        
        $result = $qb->getQuery()->getResult();
        $resultArray = array();
        foreach($result as $ingredient) {
            $resultArray[$ingredient['id']] = $ingredient['name'];
        }
        
            
        return $resultArray;
    }
}
