<?php

namespace Nutri\RecipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientForRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientForRecipeRepository extends EntityRepository
{
}
