<?php

namespace Nutri\RecipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeForShoplistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeForShoplistRepository extends EntityRepository
{
}
