<?php

namespace Nutri\RecipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShoplistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoplistRepository extends EntityRepository
{
}
